# Generated by Django 2.0.2 on 2018-03-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students', to='api.User'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tas',
            field=models.ManyToManyField(blank=True, related_name='tas', to='api.User'),
        ),
    ]
