# Generated by Django 2.0.2 on 2018-03-29 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180314_2319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',)},
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
