# Generated by Django 2.0.2 on 2018-04-22 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180328_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='student_ac',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='course',
            name='ta_ac',
            field=models.CharField(default='', max_length=30),
        ),
    ]
